### ISSUE TITLE
Is the Mining Reward constant between Peers?

### ISSUE THREAD

**Issue by cyberpunkbln** [conradoqg/naivecoin#10]
Hello,

at the moment i code at a electron gui for that and following questions are coming in mind while that coding:).

1. Was if another Client code another MinigReward? Is that checked? I mean if another user connect to the main-peer and mining and replace the Variable Reward?

2. Is it possible to split the mining and the check transactions process? I mean Miners became the Reword for the Difficulty and normal User became only the transaction fee for an simple check the transactions?

thx

**Comment by conradoqg** [comment]
Hey!

The idea is that the node should check everything, so if the miner creates a block with the wrong data/specification (mining reward or block size for example) the node will not accept the block as the next one to be added to the blockchain.

The block that survives is the block accepted by more than 51% of the nodes.

It's already kinda of separated, the miner mines the node checks and distributes.

Best

**Comment by cyberpunkbln** [comment]
Hi,

ah okay thx, then i can completly brak down this to an blockchain-only app when i want and deactivate the mining modul and replace the amount data with other data that will be hashed and checked. thx.
