### ISSUE TITLE
Miner can mine even there is no transaction

### ISSUE THREAD

**Issue by MehbubRashid** [conradoqg/naivecoin#12]
a miner can mine as much as he wants and earn coins

**Comment by conradoqg** [comment]
Yes, initially I left it like this to be easier to use it. But of course, in a real-world case, the node should ensure that a block is not accepted with empty transactions (or if it doesn't follow a threshold of transactions, size or unconfirmed transactions).

What you think I should do in this case? Do I force a minimal amount of transactions?

**Comment by conradoqg** [comment]
I've added a comment to the checkBlock method explaining the above options.
