### ISSUE TITLE
Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by khwab** [conradoqg/naivecoin#16]
First of all thank you for the contribution.

I am able to run http://localhost:3001/api-docs/ fine but when I execute POST on /operator/wallets. I get "Cannot read property 'match' of undefined" error with response code 500.

I am passing following data
{"id":"a2fb4d3f93ea3d4624243c03f507295c0c7cb5b78291a651e5575dcd03dfeeeb","addresses":[]}

I tried using command prompt too on my ubuntu 14.04 but still no luck.

My node version is 8.0.0 and npm version is 5.0.0

Please let me know what thing I am doing wrong here. 

Thank you,
Khwab

**Comment by conradoqg** [comment]
Hey

A post on /operator/wallets must contain something like this:
```
{
  "password": "string"
}
```

On swagger, the upper model is what the endpoint returns, and the right model is what the endpoint expects to receive.

Best

**Comment by khwab** [comment]
That worked, thanks a lot. It was my bad, I was only passing data and not password string.
