### ISSUE TITLE
Transaction fee destination

### ISSUE THREAD

**Issue by Andrewsopoku** [conradoqg/naivecoin#17]
Once again great work.
I would want to change the transaction fee destination from the miner's address to the receiver's address. Please how do i go about that.

**Comment by conradoqg** [comment]
Hey!

When you mine a new block you can inform the reward address. So the miner is who decides which address should receive the reward.

Best

**Comment by MarcGodard** [comment]
Transaction fees can just be put to zero.
  
EDIT: Response to your response below.
@conradoqg I think we both mis-understood. I was saying just do not have a fee, therefore there is no fee, causing the same result (the whole transaction going to the receiver's address). I am not having any issues with this code, actually quite enjoying it. Added all kinds of toys to it.

**Comment by Andrewsopoku** [comment]
What I want to do is to give the transaction fee to the address at the
output ( amount receiver ) instead of the miner address.

**Comment by conradoqg** [comment]
@Andrewsopoku 
Hey, I added the property feeAddress (as optional) to the mine endpoint, commit 088a6bb.

@MarcGodard Could you give me more details about how is that happening and where? Thanks!

**Comment by Andrewsopoku** [comment]
Great. The only issue is from the httpserver, I wouldn't know the output
address ( the address receiving the transaction amount ). I am thinking of
changing lib/miner/index.js line 57. But how to get the transaction output
address from that point is the problem.

**Comment by conradoqg** [comment]
I think I'm not getting your goal. Is this the line you are talking about?

https://github.com/conradoqg/naivecoin/blob/088a6bbb9d328b88a75124567e392d0c9cb89b87/lib/miner/index.js#L57 

Usually, the miner has his own address because he is the one spending time and energy to mine the block.

**Comment by Andrewsopoku** [comment]
I was referring to this line.
https://github.com/conradoqg/naivecoin/blob/088a6bbb9d328b88a75124567e392d0c9cb89b87/lib/miner/index.js#L102

I am looking at the miner address getting the reward as usual for the work
it does. Some People usually don't go into crytocurrencies because they
find it difficulty getting their Fiat currency back should they decide to
change their crytocurrencies into a Fiat currency ( Dollars). To motivate
People to readily receive crytocurrency and pay the sender equivalent
amount in Fiat currency, I thought of giving the receiver the transaction
fee instead of giving it to the miner.
Please I hope you get me.

**Comment by conradoqg** [comment]
I see now. I think you would need to change a couple of things:

- The miner selects the transactions that it wants to mine, so you could create a list of output transactions addresses and split the fee value by all output addresses (proportionally or not). You may want to remove the change transaction (the money that the sender receives back as a change).
- You will need to change the transaction check to enable multiple fee transactions (eg 1 for each output transaction)

Anyway, it's possible to do that and I think you have all information you need. If you want more information tell me that I can give you some source references.

Best

**Comment by kyrimedia** [comment]
Hi Conrad, do you believe that this code is ready for production ?

**Comment by conradoqg** [comment]
Hey. No, I don't believe it's ready for production. Check the // INFO comments, most of them should be implemented before putting something like naivechain to production IMO.
