### ISSUE TITLE
Same Passphrase, same AdressID

### ISSUE THREAD

**Issue by cyberpunkbln** [conradoqg/naivecoin#2]
Hello,

short issue, when i generate a wallet and use the same passphrase on a second wallet. Naivecoin generate the same AdressID for both WalletIDs. And when i transfer funds or mine, both wallets became the funds.

thx

**Comment by conradoqg** [comment]
Hey.

Yes, the wallet id is randomly generated, but the address is generated deterministically from the password. So the same password will generate the same address id. 

In the real word, usually, the password is used to encrypt/decrypt a 12-word seed and from that seed, the address is generated in a deterministic way, so from your 12-word seed, you can always create the same address (and all subsequent addresses).

Best

**Comment by cyberpunkbln** [comment]
Hello,

short an additional Question. Is that right that the mechanism of this bockchain/coin allgorythms is following:

When i have the right password i can attach Adresses to every Wallet that i have generated.

When i want to use your code for an Simple Coin-Test, is that right when i so it following:

1. Only a Button for generating a wallet without an password.
2. A Gui where the Wallet-ID can be attached with an Adress and an unique Password

Understand i that right that adress/password is the pubkey/privkey-allgorythm and the wallet-id only a container around the pubkey/privkey. The Wallet-id is not important for the blockchain?

When i use an crypto-allgyrhtm like sha256 for generating the password/privkey and del the wallet-id allgoryhtms i have a standard blockchain/bitcoin allgorythm?

thx

**Comment by conradoqg** [comment]
Yes, here we only use the wallet id as a way to "attach" de privKey/pubKey to something (that can be later referenced).

Yes, the wallet id is not important to the blockchain, it's only a feature that I created to store the keys. It could be linked to a user or anything else.

[Here](https://en.bitcoin.it/wiki/Deterministic_wallet) is a good source about how deterministic wallets are created.

Best

**Comment by cyberpunkbln** [comment]
Ah okay great i understand. I was confused why i have thinked in a 64Bytes privKey and you use 1024 for the privKey.

But one ore more questions i have:

1. When i not use the operators to create an transaction, i must create the transaction manually with the secretkey, or? Is there an REST-Argument for that without the wallet-id?

2. Can i switch easyly with an new filesystem-db to an 64Bytes-SecretKey?

thx

ps: ah i understand i must code an new this.app.post method in the http-server and new tranctions method and then remove wallet-id with secretkey?
