### ISSUE TITLE
Why i have Selected 0 candidate transactions with 4 being ignored.

### ISSUE THREAD

**Issue by demenvil** [conradoqg/naivecoin#22]
I launch curl -X POST --header 'Content-Type: application/json' -d '{ "rewardAddress": "e155df3a1bac05f88321b73931b48b54ea4300be9d1225e0b62638f537e5544c" }' 'http://localhost:3001/miner/mine'

Previously I made 5 identical transaction from one address to another.
But only the last is processed and confirmed the rest remains in the transaction list.
I also increase the number of transactions per block but nothing changes.
An idea of the problem ?

**Comment by conradoqg** [comment]
I'll check it. 

I think this is related to the fact that the 5 transactions are using the same output transaction as input transaction, so as soon as you confirm the last one, the other 4 becomes invalid (because they all are using the same "source").

I remember seeing this a while ago. I think the create transaction should be smarter and try to use the output of an unconfirmed transaction or deny the creation of another transaction while there are unconfirmed transactions (lack of confirmed funds).

**Comment by demenvil** [comment]
Ok thx,
I think it's better to use the exit of an unconfirmed transaction instead of blocked if there is an unconfirmed transaction.
Or anyway treat them all and add a controlle on the balances adresse.

**Comment by conradoqg** [comment]
I have found the way that bitcoin deals with it. It's called chain transactions. In summary, it chains the transactions and creates two groups of transactions, one with transactions that don't depend on another pending transaction and other with transactions that depend on other pending transactions.

It first consumes the transactions that don't depend on anyone and then evaluate the list of transactions that depend on others and if found another independent transaction, it moves it to the other list.

I'll think of some solution.

**Comment by conradoqg** [comment]
Hey. I added the transaction chaining feature. Please, get the commit 65a2ff6 and check if it works now for you, please.

Thanks

**Comment by demenvil** [comment]
Hi,
Nice it's work now ;)
Thx ! 


`2018-01-20T19:53:21.536Z - info - base: Broadcasting
2018-01-20T19:53:24.083Z - info - base: Selected 19 candidate transactions with 0 being rejected.
2018-01-20T19:53:24.086Z - info - base: Mining a new block with 12 (fee: 1, regular: 10, reward: 1) transactions
2018-01-20T19:53:33.241Z - info - mine-worker: Block found: time '8 sec' dif '998027618253' hash '00003dfda46e735e4af5d9f85ac3d2b6c3468f47e7a5695eccb7a13696973de7' nonce '98586'
2018-01-20T19:53:33.399Z - info - base: Block added: 00003dfda46e735e4af5d9f85ac3d2b6c3468f47e7a5695eccb7a13696973de7
2018-01-20T19:53:33.400Z - info - base: Broadcasting
`
