### ISSUE TITLE
Count Circulating Supply

### ISSUE THREAD

**Issue by demenvil** [conradoqg/naivecoin#23]
Hello, I wish to set up a count of the number of coin issued and therefore outstanding on the nodes, how would you proceed?
My idea will be to increment a file for example asset.json each validation of a transaction will be added the reward?

**Comment by conradoqg** [comment]
I think there is a very easy way to know how much was issued, just get the index of the last block and multiply by MINING_REWARD, like, if the last block is the # 50 (started at 0), then the coin circulating is 50 * 5000000000.

Best

**Comment by demenvil** [comment]
Actually it's quite simple like method!
Thank you
