### ISSUE TITLE
php-sdk

### ISSUE THREAD

**Issue by demenvil** [conradoqg/naivecoin#27]
Here is the beginning of the integration of the naivecoin API in php
[PHP SDK](https://github.com/demenvil/naivecoin-PHP-SDK)

Soon I put online an example of integration with the sdk to create wallets, explore the blochain and sent funds

**Comment by conradoqg** [comment]
Thanks man! Good job!

**Comment by conradoqg** [comment]
Hey. I'm doing some modifications in the API (not too much), check the PR #46

**Comment by demenvil** [comment]
OK ! I update in not too much time;) Thank you
