### ISSUE TITLE
Nodes syncing Wallets

### ISSUE THREAD

**Issue by Andrewsopoku** [conradoqg/naivecoin#3]
You have done a great work. well done. With the current naivecoin,If a node goes down, all wallets on it also goes down. How do i make the nodes sync wallets.

**Comment by conradoqg** [comment]
Thank you, man!

Wallets shouldn't be synced. Remember that each node in naivecoin is an operator (exchange) as well. Usually, operators are separated from the nodes and the blockchain itself. The private key (secret key) is stored in the wallet (inside the address), so if you sync that it means that every node would have the secret key, and that's not cool 😄. 

However, the node should store the wallet on the disk. If it's not doing that, I will implement it.

Sorry for the answer delay.
