### ISSUE TITLE
mining, miners, exchange

### ISSUE THREAD

**Issue by tomasko19** [conradoqg/naivecoin#34]
Hello,

im new in crypto currences, blockchain etc...
I installed Naivecoin on my server and everything is ok.
Is Naivecoin ready for mining? If yes which miner? If not how i can prepare it for mining?
Is it ready for add on any exchange? 

Thank you

**Comment by demenvil** [comment]
Hello
Everything is in the doc;)
If you do php i've coded a sdk in php that can do this stuff.
For mining, it suffices that there are transactions to validate.
Read this part => https://github.com/conradoqg/naivecoin#miner
So you have two choices.
Either undermine your own node or connect a new peer to the network
Is it ready for add on any exchange?
No I do not think the protocol may not be mature enough to be used in production.
See this project more as an educational project, allowing you to see and understand the operation of a small blockchain and cryptomony with a dedicated protocol.
good day to you

**Comment by conradoqg** [comment]
Thanks @demenvil. Closing this issue.
