### ISSUE TITLE
Change localhost into IP address

### ISSUE THREAD

**Issue by votinhthuong** [conradoqg/naivecoin#35]
I want to use the IP address instead of localhost, so that another PC can be connected to and join the blockchain network?

**Comment by conradoqg** [comment]
Hey,
    You can call naivecoin with the option `-a 0.0.0.0` to publish the service.

Best

**Comment by votinhthuong** [comment]
Thank you! But when I do as you said, in another computer in same network (LAN), I still not can't access to this blockchain?

**Comment by conradoqg** [comment]
Interesting.

What happens when you access the web UI on the same machine but using the IP instead of localhost or 127.0.0.1?

**Comment by votinhthuong** [comment]
no, that's not my mean. I mean, when I run this blockchain using my ip (example: 192.168.1.2) and when I use another computer in same LAN network (example: 192.168.1.5) access to it and it not response anything. If it can access to from another computer, so why we can demonstrate the feature peer-to-peer of the blockchain ?

**Comment by conradoqg** [comment]
Yes, I got your question right. I asked to try to access from the same machine using the IP to check if the service is responding to the correct interface (IP exposed to the LAN). If it is responding it means that the problem is not which interface selection in the service. However if you try to access from the same machine using the IP and the service is not responding, it could mean that there is a bug somewhere.

Another test that you can do is to start the naivecoin using the exposed IP instead of 0.0.0.0 (Probably this is the problem)

Meanwhile, I'm gonna test this setup here. OK?

**Comment by votinhthuong** [comment]
ya, if access from the same machine using the IP and the service is responding good. But use another machine to access to it and it can't recognize the service. 
Hope you can figure out it soon to see this blockchain for multiple clients in the network, so it can realistic instead of run all in one machine.

**Comment by votinhthuong** [comment]
Hey, how about this problem? is that true that's I just can only run the blockchain in one computer?

**Comment by votinhthuong** [comment]
@conradoqg help me this problem, please?

**Comment by conradoqg** [comment]
Hey, I've tested here and it's working, you need to explicit set the IPs, like this:
`node ./bin/naivecoin.js -a 172.19.233.46`
`node bin/naivecoin.js -a 192.168.1.3 --peers 172.19.233.46:3001`

Check it out:

![2018-05-19 17 21 06](https://user-images.githubusercontent.com/6283218/40272753-13acfe90-5b89-11e8-9a7f-a5cd94b50cae.png)

Best

**Comment by votinhthuong** [comment]
Oh wait.... 

I do same to you and it works! But, in the x.x.x.x:port/api-docs page, it return an errors in the right bottom corner. When I click into it, it open new window and said "{"schemaValidationMessages":[{"level":"error","message":"Can't read from file http://192.168.133.13:3002"}]}"

**Comment by conradoqg** [comment]
Hey,
    That link opens a validation page. Since your service is not published online (I'mean, it's not a public IP) the online validator doesn't work.

Best,

**Comment by votinhthuong** [comment]
So, how to fix this error? I try to change validatorUrl from "null" to "false" but it still get an errors?

**Comment by conradoqg** [comment]
Hey. This is not an error. That link will only work if you expose the naivecoin to the internet, using a public IP.
