### ISSUE TITLE
Can't create address for wallet when using POSTMAN

### ISSUE THREAD

**Issue by votinhthuong** [conradoqg/naivecoin#37]
I try to use POSTMAN to perform REST API for easy to look. Everything went fine, but still stuck at Create a new address for wallet step. When I use POST and set body to raw (application/json) and send this form:
{
     "password" : "a b c d e",
     "walletId" : "5084e3f06f665f62aa71aca3f06393c72dc071fc5d669df392144715301793d0"
}

It doesn't create a new address for this wallet. I'm stuck at this step, please!

**Comment by conradoqg** [comment]
What does POSTMAN say? What are the contents of the response code and body?

**Comment by votinhthuong** [comment]
ya, let me detail the problem so you can understand it. I use POSTMAN and created a new wallet with walletId like below:
{
    "id": "4da78db787d4504bafa18592d5f7940e507235154c01fa2bc8faf7cee9110857",
    "addresses": []
}

Next, I want to give it a address so that I can use for transaction. I open new tab in POSTMAN and use POST method, with URL:
localhost:3001/operator/wallets/4da78db787d4504bafa18592d5f7940e507235154c01fa2bc8faf7cee9110857/addresses

and I set "body" to raw with JSON(application/json) and the content I set:
{
	"password": "a b c d e f", //password of wallet I created before
	"walletId": "4da78db787d4504bafa18592d5f7940e507235154c01fa2bc8faf7cee9110857"
}

When I hit Send button, the results return "Wallet's password is missing." in the output. I don't know how to fix it or the correct body either URL. Please.

I attach to the image of this problem for you can see properly.

https://imgur.com/a/pR4B37B

**Comment by conradoqg** [comment]
I see. The password should be in the header: "password: a b c d e f". The password only goes in the body when creating a wallet. Everything else, if you use that wallet, the password goes in the header.

**Comment by votinhthuong** [comment]
So how to fix it?

**Comment by conradoqg** [comment]
Set the header in the POSTMAN request

**Comment by votinhthuong** [comment]
Oh, you saved me! Thanks @conradoqg <3
