### ISSUE TITLE
How to edit miner balance when they try to mine a REAL block (not a empty block)

### ISSUE THREAD

**Issue by votinhthuong** [conradoqg/naivecoin#39]
I demonstrate a situation: I have 3 peers (that's mean 3 wallet differently).
- peer 1 have a balance 5000, and he want to send peer 2 for 1000 coin.
- peer 3 will mine this transaction.
Also, I set for miner reward default is 5000, fee per transaction is 10.

After eveything done, I realise that, peer 1 will have 3990 left (that's correct), peer 2 will get 1000 (that's also correct). BUT, after peer 3 mining this transaction, he didn't get 10 coin like I expect but get 5010 coin!

How to fix this problem so that it more realistic?

**Comment by modoeblacksmith** [comment]
Set default to zero.

**Comment by votinhthuong** [comment]
If set default to zero, so peer 1 also start with 0, that's mean he can't make a transaction, so that blockchain become useless????

**Comment by votinhthuong** [comment]
Somebody help me, please!!!

**Comment by conradoqg** [comment]
If the peer 3 is mining the block, he will receive the reward `5000` so in the end `5000 + 10` in other words `reward + fee`.

**Comment by votinhthuong** [comment]
But I don't think it a good ideas. Because just mining, so that you just receive only fee coin for that, not include 5000. If anyone mining and receive 5000, so that this blockchain will become not fair.

**Comment by conradoqg** [comment]
This is how a cryptocoin like Bitcoin works, the miners are the ones who receive the reward and the fee. 

Probably you are looking for a cryptocoin that uses a proof-of-authority system or the possibility to start the blockchain with a fixed amount of coins for a given address. Without that, it would not be possible to create new coins and later transfer it.

I'm implementing the proof-of-authority option right now (it will take a few weeks) #40 . 
Next, I will do a feature to block mining (or only give the fee to the miner). No dates yet.

**Comment by votinhthuong** [comment]
ya, so hope you done it soon. I'm really like this naivecoin of yours. Last 2 days of weekend before, waiting for you to reply so long, so I look at the code and edit it a few place so that, it now can only return 'fee' coin for people who mining new block - which contain transaction in it - but not return 5000 'reward' anymore. Thank you!

**Comment by conradoqg** [comment]
Sorry to reply late, I'm quite busy these days.

May I close this issue?

**Comment by votinhthuong** [comment]
Yes, thank you!
