### ISSUE TITLE
[Question] sending specific amount of coins from one wallet to another.

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [conradoqg/naivecoin#4]
Hello.

First of all, I thank you for your work. Your code is great example for other people to learn about cryptocurrencies and blockchain, myself included.

I have several questions about making transactions.

1. I have created two wallets with one addresses then I wanted to send from one address to another 10 amounts of coins by using `/operator/wallets/{walletId}/transactions` method.

However it shows me  this error message:

     Invalid transaction balance: inputs sum '0', outputs sum '10'

I think I understand that because there are no coins at all in blockchain and I know that it there should be some kind of starting amount. 

Do I need to change **genesis block** in order to add starting amount of coins and then distribute them among other wallets?

2. What I have understood is that Nodes are storing all data of blockchain and wallets, but when I have created wallet in one node (it creates `wallets.json` file) it does not create this wallet on other node. When this new wallet will be broadcast to other nodes?

3. Do user need to be a Node in order to being able to mine new coins?

**Comment by Andrewsopoku** [comment]
Hi, to generate coins, you will need to mine them. You can still mine without having any unconfirmed transaction at least to compensate you for your energy wasted.

He already stated in the documentation that the nodes don't sync wallets. With that it will be very helpful if he could modify it.

**Comment by SuperMasterBlasterLaser** [comment]
@Andrewsopoku Thanks for answer. So wallets aren't synching in order to be able to modify it? Does bitcoin works in that kind of way, or bitcoin got something to sync wallets all over the nodes?

**Comment by Andrewsopoku** [comment]
The nodes have to sync wallets just like how they sync transactions or blocks so that when one node goes down the wallets on that node can still work.

**Comment by conradoqg** [comment]
Hey Guys,

Thanks for your comments. 
@Andrewsopoku is right, to transfer from an address to another, first, the from address must have some coins in its possession, to do that, just mine and put the address as the destination.

About the wallet question, I answered it a few seconds ago in the  #3 .
