### ISSUE TITLE
Auto discovery own IP

### ISSUE THREAD

**Issue by conradoqg** [conradoqg/naivecoin#42]
When building a multinode network it's necessary to set the IP individually. Change this to a way to find the correct IP when a node it's transmitting itself to other nodes.

**Comment by conradoqg** [comment]
Instead of discovering the IP I allowed the user to choose which address he wants to broadcast. There isn't a reliable way of getting the sender's IP. 9a308a3abe55af1b96d43597e3b8e89f4a4a0a02

**Comment by MPAds** [comment]
I know this is Javascript, but maybe this might help you if you convert it to the language you are using. I dont know c# or c++, I actually am looking for help with my github project too. lol

function getUserIP(onNewIP) { //  onNewIp - your listener function for new IPs
    //compatibility for firefox and chrome
    var myPeerConnection = window.RTCPeerConnection || window.mozRTCPeerConnection || window.webkitRTCPeerConnection;
    var pc = new myPeerConnection({
        iceServers: []
    }),
    noop = function() {},
    localIPs = {},
    ipRegex = /([0-9]{1,3}(\.[0-9]{1,3}){3}|[a-f0-9]{1,4}(:[a-f0-9]{1,4}){7})/g,
    key;

    function iterateIP(ip) {
        if (!localIPs[ip]) onNewIP(ip);
        localIPs[ip] = true;
    }

     //create a bogus data channel
    pc.createDataChannel("");

    // create offer and set local description
    pc.createOffer(function(sdp) {
        sdp.sdp.split('\n').forEach(function(line) {
            if (line.indexOf('candidate') < 0) return;
            line.match(ipRegex).forEach(iterateIP);
        });
        
        pc.setLocalDescription(sdp, noop, noop);
    }, noop); 

    //listen for candidate events
    pc.onicecandidate = function(ice) {
        if (!ice || !ice.candidate || !ice.candidate.candidate || !ice.candidate.candidate.match(ipRegex)) return;
        ice.candidate.candidate.match(ipRegex).forEach(iterateIP);
    };

}

getUserIP(function(ip){
	document.getElementById("ipaddress").innerHTML = 'Your IP = '  + ip + "";  // public ip    &    local IP
	var walletHash = ip;    // 192.168.1.67 @ home  // 192.168.10.130 @ Panera   // console.log( walletHash);
	var sVal = walletHash;
    var iNum = parseInt(sVal, 16); //Output 402 and 9728 and toString32 = ci and 9g0    //(305441741).toString(16) = "1234abcd"

 
 salt = (927 ^ 54 > 5^70)
 sum = (iNum * iNum * salt);    // 
 WalletAddress = sum.toString(26); // Output d9pc5m and bfbc0ipe    // console.log( WalletAddress);
 document.getElementById("wallet").innerHTML = 'Your Wallet Address = '  + WalletAddress + "";  //  WalletAddress;


});
