### ISSUE TITLE
Is there anyway to call rest API not using swagger?

### ISSUE THREAD

**Issue by votinhthuong** [conradoqg/naivecoin#45]
Can you implementing a simple call rest API for view all blocks of blockchain but not using swagger. 

I means, please, demonstrate a separate html javascript file that include javascript inside it for call rest API to view all blocks in blockchain.

I don't know how and where to begin!

**Comment by conradoqg** [comment]
Yes. Swagger is a simple UI to help you explore the API. This means that you can do the same thing using any other HTTP Client.

You can google about this or access one of the links below to learn how to do this:
- https://www.kirupa.com/html5/making_http_requests_js.htm
- https://www.w3schools.com/jquery/ajax_get.asp
and so on...

Best
