### ISSUE TITLE
Is mining done on the serverside?

### ISSUE THREAD

**Issue by AkshatJain2005** [conradoqg/naivecoin#50]
i wonder if mining is done on the serverside or the clientside and how can we make a miner for this mining process?

**Comment by conradoqg** [comment]
The mining is done on the server side in another thread. I didn't get the second part of your question.

**Comment by AkshatJain2005** [comment]
How can we make it so we can mine through the client side

**Comment by AkshatJain2005** [comment]
So it is actual mining

**Comment by conradoqg** [comment]
> How can we make it so we can mine through the client side

It can be developed. The main challenge is to not freeze the client, mining is quite processor heavy (maybe using workers?).

Best

**Comment by MPAds** [comment]
Send the mining to the GPU with GPU.js
