### ISSUE TITLE
POS implementation ?

### ISSUE THREAD

**Issue by crashbdx** [conradoqg/naivecoin#52]
Hello,

Thank you very much for this very interesting work.
Would a proof of stake implementation concept be possible on this project ?
Also what make this project not suitable for real world usage on basic dapps like proof of existence or things like that ?

Thank you

**Comment by conradoqg** [comment]
I implemented it on branch v1.0.0 (I'm waiting for someone to test it)

There are a lot of features that would need to be implemented, especially regarding security, difficulty formula and so on. We discuss that in other issues that you can find here.

Best,

**Comment by crashbdx** [comment]
Thanks a lot for your reply, how can we help testing it ?do we have to deploy online ? im willing to help as im interested to learn at the same time :)

Will search for the topic that discuss the needed work for it eventually work on real world then, thanks again.

**Comment by conradoqg** [comment]
You could start by understanding the inner work of this coin using branch v1.0.0 as a reference.

**Comment by crashbdx** [comment]
Ok will start doing that thank you :)

**Comment by MPAds** [comment]
I reviewed the POW file, v1 but nothing specifically named POS. I was reviewing the question by crashbdx  asking about POS. My experience with SHA 256 is that it consumes the CPU and can be a runaway train, lol, I also look at POA and I believe this is what decides if the wallet can stake?

**Comment by crashbdx** [comment]
I did check as well but didn't see any mention of POS, is it the Proof of authority ?
