### ISSUE TITLE
Mining Worker (worker.js & slave.js) Never Closes

### ISSUE THREAD

**Issue by DimensionDevices** [conradoqg/naivecoin#56]
I think I have found a "memory leak" of sorts. 

When the mining finishes, the worker/slave combo doesn't actually close the mining thread... Which causes this..

https://i.imgur.com/UmJESwc.png

So, the worker.js file has a "kill" function within them, but I can't figure out how to auto kill the process once mining has stopped (otherwise memory just fills up....)

Any ideas?

**Comment by DimensionDevices** [comment]
No one know how to kill the slave/worker...?

**Comment by conradoqg** [comment]
I'll look into it.

**Comment by DimensionDevices** [comment]
@conradoqg - I appreciate that mate. I've been looking for a while now. It means I can't run for any longer than my RAM allows, that is frustrating

🤣

**Comment by conradoqg** [comment]
Hey, fixed it in 9116c573641d77726b020b308c31f9726a5788fb

Thanks!

**Comment by DimensionDevices** [comment]
@conradoqg - That's why you da man! Gracias amigo!
