### ISSUE TITLE
Cost of Proof of Work

### ISSUE THREAD

**Issue by subversivo58** [conradoqg/naivecoin#7]
Is it possible to maintain an effective cost of **proof of work** without being necessarily exponential?

I mean, a cost that determines that there was a computational effort but that it does not penalize subsequent "miners"?

**Comment by conradoqg** [comment]
Yes, it's possible, you just need to hardcode the difficulty value. 

Just change this method https://github.com/conradoqg/naivecoin/blob/71fce56057dcc6769ccc79a2cb14c5e4f1d8f9e4/lib/blockchain/index.js#L67-L79 and give it a constant value. (You can use de BASE_DIFFICULTY - \<some number\>)

This change will make the difficulty to not increase as blocks are mined, the difficulty will be constant.

**Comment by subversivo58** [comment]
Thanks
